Repository bethinkpl/wnl-platform, pull requests merged in 2018-10, with the labels that each got.

#1086 Fix orderPaid job falling into an infinite loop (again)
  app/Observers/OrderObserver.php
Labels: ready

#1087 100% coupon marks order as paid when attached from /orders tab
  app/Http/Controllers/Api/PrivateApi/OrdersApiController.php
Labels: ready

#1088 Add Recently Correct, Recently Incorrect filters
  app/Http/Controllers/Api/Filters/Quiz/ResolutionFilter.php
  app/Http/Controllers/Api/PrivateApi/QuizQuestionsApiController.php
  resources/assets/js/components/questions/QuestionsPlanProgress.vue
  resources/assets/js/i18n/pl/questions.js
Labels: ready

#1089 [PLAT-616] Render missing invoices
  app/Console/Commands/FixMissingInvoiceFiles.php
  app/Console/Commands/InvoiceRender.php
  app/Console/Commands/MigrateInvoiceType.php
  app/Models/Invoice.php
  database/migrations/2018_10_10_140959_add_type_to_invoices.php
  lib/Invoice/Invoice.php
Labels: ready

#1084 update satisfaction guarantee copy
  resources/assets/js/components/user/plan/PlanGuarantee.vue
Labels: code review required

#1098 [PLAT-622] Unassign tasks command
  app/Console/Commands/UnassignTasks.php
Labels: ready

#1095 SAD
  app/Http/Controllers/AppController.php
  resources/assets/js/app.js
  resources/assets/js/components/App.vue
  resources/assets/js/components/chat/MessagesList.vue
  resources/assets/js/components/chat/PrivateChat.vue
  resources/assets/js/components/chat/PublicChat.vue
  resources/assets/js/components/collections/SlidesCarousel.vue
  resources/assets/js/components/course/Lesson.vue
  resources/assets/js/components/course/Screen.vue
  resources/assets/js/components/course/screens/slideshow/Slideshow.vue
  resources/assets/js/components/quiz/SingleQuestion.vue
  resources/assets/js/components/quiz/SingleQuestionRedirect.vue
  resources/assets/js/consts/events_map/context.json
  resources/assets/js/consts/events_map/features.json
  resources/assets/js/mixins/emits-events.js
  resources/assets/js/plugins/chat-connection.js
  resources/assets/js/plugins/events-tracker.js
  resources/assets/js/router.js
  resources/assets/js/store/modules/chatMessages.js
Labels: work in progress

#1101 [PLAT-647] Remove moderators work info
  resources/assets/js/components/course/dashboard/Overview.vue
Labels: code review required

#1097 add comment with PLAT-641 link
  app/Models/Order.php
Labels: code review required
