Repository bethinkpl/wnl-platform, pull requests merged in 2019-04, with the labels that each got.

#1391 Fix product editor crashing when product has no instalments
  resources/assets/js/admin/components/products/ProductPaymentMethods.vue
Labels: P4, no ticket

#1417 [PLAT-1199] FAQ pages
  resources/assets/js/components/help/Help.vue
  resources/assets/js/i18n/pl/routes.js
  resources/assets/js/router.js
Labels: code review required

#1445 PLAT-1248 | log resource update in database
  app/Http/Controllers/Api/PrivateApi/QnaQuestionsApiController.php
  app/Http/Requests/Qna/UpdateQuestion.php
  app/Models/Comment.php
  app/Models/QnaAnswer.php
  app/Models/QnaQuestion.php
  app/Models/User.php
  app/Observers/QnaQuestionObserver.php
  composer.json
  composer.lock
  config/accountant.php
  database/migrations/2019_04_19_115158_add_verified_at_column.php
  database/migrations/2019_04_23_000001_create_ledgers_table.php
  tests/Api/Qna/QuestionsTest.php
Labels: work in progress
